# .github/workflows/rubocop-analysis.yml
name: "RuboCop"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  rubocop:
    name: Guidelines checks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.4
        bundler-cache: true
